[package]
name = "surfql-downloader"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
surfql-storage = { path = "../surfql-storage", features = ["telemetry"] }
surfql-queue = { path = "../surfql-queue" }
async-trait.workspace = true
futures.workspace = true
reqwest.workspace = true
thiserror.workspace = true
rand.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[lints]
workspace = true
